name: deploy_dev
on:
  workflow_dispatch:
jobs:
  manual_deploy:
    runs-on: dev-html
    steps: 
      - uses: actions/checkout@v2
      - run: cd /var/www/html/
      - run: git -C /var/www/html/ pull origin main
        env:
          CI: true
